name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Build the Docker image
        # env:
        #   DOCKER_BUILDKIT: 1
        run: docker buildx build --platform linux/amd64 --iidfile imagename .

      - name: Tag the Docker image
        env:
          PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}
        run: |
          docker tag $(cat imagename) "ghcr.io/$(echo $GITHUB_REPOSITORY):$(echo $PACKAGE_VERSION)"
          docker tag $(cat imagename) "ghcr.io/$(echo $GITHUB_REPOSITORY):latest"
